### ISSUE TITLE
Can't connect nextcloud or Android app, healthcheck URL returns a 400 error

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/onlyoffice_ynh#63]
### Describe the bug

Installation went fine, but OO is unusable via Nextcloud or the Android app - probably because the address https://<documentserver>/healthcheck returns a 400 error

### Context

- Hardware: VPS on Linode
- YunoHost version: 
```
root@ynh:~# yunohost -v
yunohost:
  repo: stable
  version: 4.2.6.1
yunohost-admin:
  repo: stable
  version: 4.2.3.3
moulinette:
  repo: stable
  version: 4.2.3.3
ssowat:
  repo: stable
  version: 4.2.3
```
- I have access to my server: SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 6.1.0~ynh2

### Steps to reproduce

- Install OO.
- Install OO Nextcloud app.
- Put the OO URL in the config of the nextcloud app
- A 400 error is returned saying that the address https://<documentserver>/healthcheck is not found

### Expected behavior

Well, for the nextcloud app to succeed in connecting to OO ;)

### Logs

I found this in the documentserver/nginx.error.log:
```
2021/08/07 22:52:00 [error] 30035#30035: *1040 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /healthcheck/ HTTP/1.1", upstream: "http://[::1]:8000/healthcheck/", host: "[my obfuscated documentserverURL]"
```
When I look at the nginx configuration for the documentserver, it's not running on port 8000 but on 8096, might this be the issue?
